apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
spec:
  entrypoint: verify-host
  arguments:
    parameters:
    - name: harbor_host
  templates:
  - name: verify-host
    inputs:
      parameters:
      - name: harbor_host
    container:
      image: alpine
      command: [sh, -c]
      args: ['echo "harbor_host: $HARBOR_HOST"']
      env:
      - name: HARBOR_HOST
        value: "{{inputs.parameters.harbor_host}}"

