name: style

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        OUTPUT=$(pylint ./ --exit-zero)
        echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
    - name: Post result to PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          **Style checker output:** test123
          ${{ env.MESSAGE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
